sqlite3mem: &SQLITE3MEM
  adapter: sqlite3
  database: ":memory:"

sqlite3: &SQLITE
  adapter: sqlite3
  database: acts_as_audited_plugin.sqlite3.db

jrubysqlite3mem: &JRUBYSQLITE3MEM
  adapter: jdbcsqlite3
  database: ":memory:"

jrubysqlite3: &JRUBYSQLITE
  adapter: jdbcsqlite3
  database: acts_as_audited_plugin.sqlite3.db

postgresql: &POSTGRES
  adapter: postgresql
  username: postgres
  password: postgres
  database: acts_as_audited_plugin_test
  min_messages: ERROR

mysql: &MYSQL
  adapter: mysql
  host: localhost
  username: root
  password:
  database: acts_as_audited_plugin_test

test:
  <<: *<%= ENV['DB'] || 'SQLITE3MEM' %>
